# Generated by Django 6.0.5 on 2026-05-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'हिंदी'), ('mr', 'मराठी')], default='en', max_length=5),
        ),
    ]
