from django.urls import path
from . import views

urlpatterns = [
    path('', views.medicine_list, name='medicine_list'),
    path('add/', views.add_medicine, name='add_medicine'),
    path('mark/<int:med_id>/', views.mark_medicine, name='mark_medicine'),
    path('detail/<int:med_id>/', views.medicine_detail, name='medicine_detail'),
    path('delete/<int:med_id>/', views.delete_medicine, name='delete_medicine'),
    path('activities/', views.activity_list, name='activity_list'),
    path('activities/log/', views.log_activity, name='log_activity'),
    path('activities/<int:activity_id>/edit/', views.edit_activity, name='edit_activity'),
    path('activities/<int:activity_id>/delete/', views.delete_activity, name='delete_activity'),
    path('activities/<int:activity_id>/', views.activity_detail, name='activity_detail'),
    path('activities/reminders/', views.activity_reminder_status, name='activity_reminder_status'),
    path('activities/start/<int:log_id>/', views.start_activity_session, name='start_activity_session'),
    path('activities/session/<int:log_id>/', views.activity_session, name='activity_session'),
    path('activities/complete/<int:log_id>/', views.complete_activity_session, name='complete_activity_session'),
    path('activities/skip/<int:log_id>/', views.skip_activity_session, name='skip_activity_session'),
    path('activities/snooze/<int:log_id>/', views.snooze_activity_reminder, name='snooze_activity_reminder'),
    path('activities/ack-reminder/<int:log_id>/', views.ack_activity_reminder, name='ack_activity_reminder'),
    path('health-check/', views.daily_health_check, name='daily_health_check'),
    path('analytics/', views.health_analytics, name='health_analytics'),
    path('family-contacts/', views.family_contacts, name='family_contacts'),
    path('reminders/', views.medicine_reminder_status, name='medicine_reminder_status'),
    path('reminders/snooze/<int:log_id>/', views.snooze_medicine_reminder, name='snooze_medicine_reminder'),
    path('reminders/ack/<int:log_id>/', views.ack_medicine_reminder, name='ack_medicine_reminder'),
    path('risk-alerts/', views.health_risk_alerts, name='health_risk_alerts'),
    path('find-pharmacies/', views.find_pharmacies, name='find_pharmacies'),
    path('edit/<int:med_id>/', views.edit_medicine, name='edit_medicine'),
    path('inventory-alerts/', views.inventory_alerts, name='inventory_alerts'),
    path('inventory-dismiss/<int:med_id>/', views.dismiss_inventory_alert, name='dismiss_inventory_alert'),
    path('quick-refill/<int:med_id>/', views.quick_refill_medicine, name='quick_refill_medicine'),
    path('refill/<int:med_id>/', views.refill_medicine, name='refill_medicine'),
]
