# Generated by Django 6.0.5 on 2026-05-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_mode',
            field=models.CharField(choices=[('in_person', 'In-Person'), ('video', 'Video Consultation'), ('both', 'Both')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('moderate', 'Moderate'), ('active', 'Active')], max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='alcohol_consumption',
            field=models.CharField(blank=True, choices=[('no', 'None'), ('occasional', 'Occasional'), ('moderate', 'Moderate'), ('heavy', 'Heavy')], max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_donor_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='chronic_diseases',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='diabetes',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('type1', 'Type 1'), ('type2', 'Type 2'), ('pre', 'Pre-diabetic')], max_length=10),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='doctor_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='exercise_frequency',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('rarely', 'Rarely'), ('sometimes', 'Sometimes'), ('daily', 'Daily')], max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='primary_doctor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='smoking_habit',
            field=models.CharField(blank=True, choices=[('no', 'Non-smoker'), ('occasional', 'Occasional'), ('regular', 'Regular'), ('ex', 'Ex-smoker')], max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
