# Generated by Django 6.0.5 on 2026-05-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_add_extended_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='enable_sos',
            field=models.BooleanField(default=False),
        ),
    ]
