# Generated by Django 6.0.5 on 2026-05-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_add_cancellation_video_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date', '-appointment_time']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('system', 'System')], max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='emergency_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('missed', 'Missed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='video_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='video_session_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
