# Generated by Django 6.0.5 on 2026-05-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='call_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='call_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='timeout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending_doctor_confirmation', 'Pending Doctor Confirmation'), ('pending_confirmation', 'Pending Confirmation'), ('doctor_confirmed', 'Doctor Confirmed'), ('patient_confirmed', 'Patient Confirmed'), ('confirmed', 'Confirmed'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('ended', 'Ended'), ('cancelled', 'Cancelled'), ('cancelled_by_patient', 'Cancelled by Patient'), ('cancelled_by_doctor', 'Cancelled by Doctor'), ('rejected', 'Rejected'), ('doctor_unavailable', 'Doctor Unavailable'), ('timeout', 'Timeout')], default='pending', max_length=30),
        ),
    ]
