# Generated by Django 6.0.5 on 2026-05-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_alter_medicinelog_marked_by_alter_riskscore_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhealthcheck',
            name='feeling',
            field=models.CharField(choices=[('good', 'Good'), ('okay', 'Okay'), ('not_good', 'Not Good'), ('custom', 'Custom')], max_length=10),
        ),
    ]
