# Generated by Django 6.0.5 on 2026-05-29 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_alter_dailyhealthcheck_feeling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_medicines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicine',
            name='deletion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='color',
            field=models.CharField(default='blue', max_length=30),
        ),
    ]
