# Generated by Django 6.0.5 on 2026-05-30 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_doctor_dashboard_fixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='prescribed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='repeat_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='activity',
            name='schedule_type',
            field=models.CharField(choices=[('one_time', 'One Time Activity'), ('daily', 'Daily Activity'), ('weekly', 'Weekly Activity'), ('custom', 'Custom Schedule')], default='one_time', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='severity',
            field=models.CharField(choices=[('low', 'Low Impact'), ('medium', 'Medium Impact'), ('high', 'High Impact')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='time_slots',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('exercise', 'Exercise'), ('walking', 'Walking'), ('yoga', 'Yoga'), ('physiotherapy', 'Physiotherapy'), ('dialysis', 'Dialysis'), ('bp_check', 'Blood Pressure Check'), ('sugar_check', 'Blood Sugar Check'), ('breathing', 'Breathing Exercise'), ('diet', 'Diet'), ('meditation', 'Meditation'), ('sleep', 'Sleep'), ('doctor_recommended', 'Doctor Recommended'), ('vitals', 'Vitals Check'), ('symptom', 'Symptom Report'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='activity',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('missed', 'Missed'), ('skipped', 'Skipped')], default='scheduled', max_length=15)),
                ('proof_upload', models.FileField(blank=True, null=True, upload_to='activities/proof/')),
                ('notes', models.TextField(blank=True)),
                ('reminder_count', models.IntegerField(default=0)),
                ('missed_reason', models.TextField(blank=True)),
                ('duration_completed_minutes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='medicines.activity')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_time'],
                'unique_together': {('activity', 'scheduled_time')},
            },
        ),
    ]
