# Generated by Django 6.0.5 on 2026-05-30 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0006_activity_scheduling_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='reminders_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='requires_proof',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='severity',
            field=models.CharField(choices=[('low', 'Low Impact'), ('medium', 'Medium Impact'), ('high', 'High Impact'), ('critical', 'Critical Impact')], default='low', max_length=10),
        ),
        migrations.CreateModel(
            name='ActivityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=10)),
                ('scope', models.CharField(blank=True, choices=[('occurrence', 'This occurrence only'), ('future', 'Future schedules'), ('entire', 'Entire schedule')], max_length=15)),
                ('reason', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='medicines.activity')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
