# Generated by Django 6.0.5 on 2026-05-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0007_activity_audit_and_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
