# Generated by Django 6.0.5 on 2026-05-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='priority_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='receive_emergency_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
