# Generated by Django 6.0.5 on 2026-05-29 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0002_caregiverprofile_date_of_birth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiverprofile',
            name='caregiver_type',
            field=models.CharField(choices=[('family', 'Family Caregiver'), ('personal', 'Personal Caregiver'), ('hospital', 'Hospital Caregiver'), ('private_center', 'Private Care Center'), ('nursing', 'Nursing Caregiver'), ('home_nurse', 'Home Nurse'), ('elderly', 'Elderly Caregiver'), ('other', 'Other')], default='personal', max_length=20),
        ),
        migrations.CreateModel(
            name='PatientCaregiverRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caregiver_name', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('caregiver_type', models.CharField(choices=[('family', 'Family Caregiver'), ('personal', 'Personal Caregiver'), ('hospital', 'Hospital Caregiver'), ('private_center', 'Private Care Center'), ('nursing', 'Nursing Caregiver'), ('home_nurse', 'Home Nurse'), ('elderly', 'Elderly Caregiver'), ('other', 'Other')], default='personal', max_length=30)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by_label', models.CharField(choices=[('family', 'Family'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('caregiver', 'Caregiver')], default='doctor', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregiver_records_assigned', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregiver_record', to='caregiver.caregiverpatientassignment')),
                ('caregiver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_caregiver_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
