# Generated by Django 6.0.5 on 2026-05-29 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0003_doctor_dashboard_fixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalCaregiverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caregiver_name', models.CharField(max_length=200)),
                ('caregiver_role', models.CharField(choices=[('hospital_caregiver', 'Hospital Caregiver'), ('clinical_assistant', 'Clinical Assistant'), ('nurse', 'Nurse'), ('emergency_support', 'Emergency Support'), ('elderly_support', 'Elderly Support'), ('monitoring_staff', 'Monitoring Staff'), ('recovery_assistant', 'Recovery Assistant')], default='hospital_caregiver', max_length=30)),
                ('department', models.CharField(choices=[('icu', 'ICU'), ('dermatology', 'Dermatology'), ('cardiology', 'Cardiology'), ('general_care', 'General Care'), ('emergency', 'Emergency'), ('other', 'Other')], default='general_care', max_length=30)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('responsibilities', models.TextField(blank=True)),
                ('duration_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary')], default='permanent', max_length=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('removed', 'Removed'), ('replaced', 'Replaced')], default='active', max_length=15)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_caregivers_assigned', to=settings.AUTH_USER_MODEL)),
                ('caregiver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_caregiver_roles', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_caregiver_assignments', to=settings.AUTH_USER_MODEL)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_caregivers_removed', to=settings.AUTH_USER_MODEL)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_assignment', to='caregiver.hospitalcaregiverassignment')),
                ('system_assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_assignment', to='caregiver.caregiverpatientassignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
