# Generated by Django 6.0.5 on 2026-05-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_category_notification_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('medicine', 'Medicine'), ('activity', 'Activity'), ('appointment', 'Appointment'), ('connection', 'Connection'), ('report', 'Report'), ('alert', 'Alert'), ('message', 'Message'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
